print("Step 1: Game loaded")
local lp = game:GetService("Players").LocalPlayer
local PlayerGui = lp:WaitForChild("PlayerGui")
local INTERFACE = PlayerGui:WaitForChild("Interface")
print("Step 2: Interface found:", INTERFACE)
local remotesFolder = game:GetService("ReplicatedStorage"):WaitForChild("Assets"):WaitForChild("Remotes")
local getRemote = remotesFolder:WaitForChild("GET")
print("Step 3: Remotes found")
local mapData = getRemote:InvokeServer("Data", "Copy")
print("Step 4: mapData:", mapData)
local lastPlayerData = getRemote:InvokeServer("Functions", "Settings", "Get")
print("Step 5: playerData:", lastPlayerData)
